services:
  frontend:
    build: frontend
    platform: linux/amd64  # lightning css not compatible with arm
    profiles: ["frontend"]
    environment:
      - WORDPRESS_CMS_PUBLIC_URL=${WORDPRESS_CMS_PUBLIC_URL}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - FRONTEND_NEXTJS_PASSWORD=${FRONTEND_NEXTJS_PASSWORD}
    ports:
       - ${FRONTEND_EXPOSE_PORT}:3000
    restart: always

  # WordPress cms
  wordpress:
    image: wordpress:6.8.3-php8.2-apache
    environment:
      - WORDPRESS_DB_NAME=wp_db
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    ports:
      - ${WORDPRESS_EXPOSE_PORT}:80
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:lts-noble
    environment:
      - MARIADB_DATABASE=wp_db
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - wordpress-mariadb-db:/var/lib/mysql
    restart: always

  # WordPress initial setup and configuration
  wp-setup:
    build: wordpress-cms-setup
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    environment:
      # Waiting for mariadb and wordpress -------------------
      - WAIT_HOSTS=mariadb:3306,wordpress:80
      # WordPress configuration -----------------------------
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wp_db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - WORDPRESS_CMS_PUBLIC_URL=${WORDPRESS_CMS_PUBLIC_URL}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - FRONTEND_NEXTJS_PASSWORD=${FRONTEND_NEXTJS_PASSWORD}
    restart: "no"

  # Command line interface for WordPress
  wpcli:
    image: wordpress:cli
    profiles: ["wpcli"]
    user: "33:33"  # www-data user
    environment:
      - WORDPRESS_DB_NAME=wp_db
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
      - mariadb

volumes:
  wordpress:
  wordpress-mariadb-db:
