fragment AuthorDetailsFields on NodeWithAuthor {
    author {
        node {
            name
            firstName
            lastName
            avatar {
                url
            }
        }
    }
}
